@startmindmap
* Application Insights
** Enablement Methods
*** Auto-Instrumentation (agent)
*** Application Insights SDK
** Benefits of Auto-Instrumentation
*** No developer investment
*** Eliminates future overhead
*** Source code accessibility
** List of Supported Services
*** Rapidly changing
*** [Visit this page](https://example.com) for an up-to-date list
** Circumstances for SDK Installation
*** Custom events and metrics
*** Control over telemetry flow
*** Auto-Instrumentation not available
** SDK Instrumentation
*** Web app
*** Background components
*** JavaScript within web pages
** Telemetry Data Flow
*** Directed to Application Insights resource
*** Unique token
** Native Distributed Tracing Support
*** .NET
*** .NET Core
*** Java
*** Node.js
*** JavaScript
** Manual Tracking with TrackDependency
** OpenCensus
*** Open-source distribution of libraries
*** Metrics collection and distributed tracing
*** Enables distributed tracing with popular technologies
**** Redis
**** Memcached
**** MongoDB
@endmindmap
