@startmindmap
* Main Concepts
** Deployment Monitoring
*** Recurring tests
**** Availability
**** Responsiveness
** Application Insights
*** Sends web requests
**** Regular intervals
**** Worldwide points
*** Availability Tests
**** HTTP/HTTPS endpoints
**** No website changes
**** REST API testing
*** Test Types
**** URL ping test (classic)
**** Standard test (Preview)
**** Custom TrackAvailability test
**** Multi-step test (Visual Studio 2019)
*** URL Ping Test
**** DNS infrastructure reliance
*** Standard Test
**** SSL certificate validity
**** Proactive lifetime check
**** HTTP request verb
**** Custom headers
**** Custom data
*** Custom TrackAvailability Test
**** Results sent via TrackAvailability()
*** Multi-step Test
**** Complex scenarios
**** Multiple requests
**** Authentication
*** Private DNS
**** Custom TrackAvailability tests
**** DNS resolution
***** Public domain name servers
@endmindmap
