@startmindmap "Application Insights"

+ Application Insights

'++ Features
'+++_ Live Metrics
'+++_ Availability
'+++_ GitHub or Azure DevOps integration
'+++_ Usage
'+++_ Smart Detection
'+++_ Application Map
'+++_  Distributed Tracing


++ Metric
+++ Log-based metrics
++++_ Translated into Kusto queries from stored events
++++_ Great analytical and diagnostic value
++++_ Significantly improve visibility into the application health and usage
++++ Telemetry volume reduction
+++++_ Reduces the number of collected and stored events
+++++_ Also lowers the accuracy of the metrics
+++ Pre-aggregated metrics
++++_ Stored as pre-aggregated time series
++++_ Pre-aggregated during collection
++++ Better query performance
+++++ Dashboarding
+++++ Real-time alerting
++++ SDKs
+++++_ Application Insights 2.7 and later
++++++_ Pre-aggregate during collection
++++++_ Less data ingestion and lower cost
+++++_ Older versions...
++++++_ Still pre-aggregates before sampling

+ Instrumentation
++ Auto-instrumentation
+++_ No developer investment
+++_ Without access to source code
++++_ Requires
+++++_ Enabling
+++++_ In some cases, configuring the agent
++ Application Insights SDKs
+++_ When require
++++_ Custom events and metrics
++++_ Control over flow of telemetry
+++_ Or when
++++_ Auto-instrumentation not available (language or platform limitations)

++ OpenCensus
+++_ OpenCensus is an open source, vendor-agnostic, single distribution of libraries
+++_ Enable distributed tracing with Redis, Memcached, or MongoDB...

+ Availability Tests
++_ Any HTTP or HTTPS endpoint accessible via public internet
++ No changes to website necessary
+++_ Sites you own
+++_ Sites you don't own
+++_ REST API your service depends on
++ Limit
+++_ 100 availability tests per Application Insights resource
++ Types
+++ URL ping test
++++_ Created in Portal
++++_ Measure response and performance
++++_ set
+++++_ Custom success criteria
+++++_ Parse dependent requests
+++++_ Allow for retries
+++ Standard test (Preview)
++++ URL test with... 
+++++_ SSL certificate validity
+++++_ Proactive lifetime check
+++++_ HTTP Request
++++++_ Verb (GET, POST...)
++++++_ Custom headers
++++++_ Custom data
+++ Custom TrackAvailability
++++_ Use custom application to run tests
++++_ TrackAvailability()

+ Application Map

++_ Visualize complex topologies with hundreds of components
++_ Spot performance bottlenecks or failure hotspots
++ Application node
+++_ a Component
++++_ Dependencies
++++_ Health KPI
++++_ Alerts status

@endmindmap