@startmindmap "Application Insights monitors"

+ ???
++_ Which pages are most popular\n     and at what time of the day?\nWhere are your users?\nWhich pages perform best?\nDo you have a resourcing problem?
+++_ use
++++ AJAX calls
+++ Request Rates
+++ Response Times
+++ Failure Rates

++_ What external services are slowing you down?
+++ Dependency Rates
+++ Response Times
+++ Failure Rates

++_ Analyze aggregated exception statistics\nPick and drill into stack trace\nServer and browser
+++ Exceptions


--_ What's being reported by your user's browsers?
--- Page Views
--- Load performance

--_ How popular are you?
--- User counts
--- Session counts

--_ How healthy are your resources?
---_ Windows and Linux server machines\nCPU, memory and network usage
---- Performance counters
---_ Docker or Azure
---- Host diagnostics

--_ Correlate trace events with requests
--- Diagnostic trace logs

--_ Track business events\nItems sold or games won
--- Custom events and metrics


@endmindmap